server:
  port: 80
  # 指定项目名
  #servlet:
    #context-path: /test
spring:
  mvc:
    view:
      prefix: /WEB-INF/pages
      suffix: .jsp
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/case?useSSL=true&charset=utf8mb4&serverTimezone=Hongkong
    username: xxxxx
    password: xxxxx
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:  # Redis数据库索引（默认为0）
    database: '0'
    host: xxxxx  #Redis服务器地址
    port: 6379  # Redis服务器连接端口
    password:
    pool:
      jedis:
        max-active: 500  # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1  # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 10 # 连接池中的最大空闲连接
        min-idle: 0  # 连接池中的最小空闲连接
    timeout: 10000 # 连接超时时间（毫秒）
mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.bmw.seed.model

# '/?([-|\w]+)?/test/(\w)+'： ?([-|\w]+)?表示任何地址出现0或1次，test，(\w)+表示具体的请求
auth:
  login:
    pattern: '/?([-|\w]+)?/test/(\w)+'
    loginUrl: http://127.0.0.1/mock/login
    host: http://127.0.0.1