server:
  port: 80

##配置数据库信息

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bimowu?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT
    username: root
    password: lishanshan
    type: com.alibaba.druid.pool.DruidDataSource

  redis:  # Redis数据库索引（默认为0）
    database: '0'
    host: localhost  #Redis服务器地址
    port: 6379  # Redis服务器连接端口
    password:
    pool:
      jedis:
        max-active: 500  # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1  # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 10 # 连接池中的最大空闲连接
        min-idle: 0  # 连接池中的最小空闲连接
    timeout: 10000 # 连接超时时间（毫秒）
mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.bmw.seed.model


#http:
#  maxTotal: 300
#  defaultMaxPerRoute: 50
#  connectTimeout: 1000
#  connectionRequestTimeout: 500
#  socketTimeout: 5000
#  staleConnectionCheckEnabled: true
